export const enum IconsPath {
  VITE_ICON = 'vite-icon',
  SQUARE_ICON = 'square-icon',
  SEARCH_ICON = 'search-icon',
  NOTIFICATION = 'notification-icon',
  CHEVRON_ICON = 'chevron-icon',
  CONNECT_ICON = 'connect-icon',
  PATIENT_ICON = 'patient-icon',
  MEDICAL_ICON = 'medical-icon',
  SETTING_ICON = 'setting-icon',
  DOTS_ICON = 'dots-icon',
  MESSAGE_ICON = 'message-icon',
  PLUS_ICON = 'plus-icon',
  EYE_ICON = 'eye-icon',
  SPINNER_ICON = 'spinner-icon',
  DONE_ICON = 'dont-icon',
  CLOSE_ICON = 'close-icon',
  PENCIL_ICON = 'pencil-icon',
}
